### ISSUE TITLE
Not working properly on the Android app

### ISSUE THREAD

**Issue by ned-si** [hyphone/sn-theme-vscode#2]
The theme is beautiful and works great on desktop. 

Unfortunately, the Android app doesn't work when entering a note. Indeed, the tasks list and the tags list are fine, but the actual notes are showing in a light theme (the default one maybe?).

Would that be something supported at some point or is it out of scope?

Cheers!

**Comment by marcolaux** [comment]
Hi there and thank you for the interest.

I haven't updated it for quite a while as I'm not using Standard Notes anymore.
But the last time I tried it was about two months ago and it still worked.
Now it seems they changed some variables and classes that I would need to adjust.

I'm quite busy at the moment but hopefully can have a look at it in mid September.
But I can't promise this as time is not my best friend right now.

**Comment by ned-si** [comment]
Hi,

Thanks for the quick answer!

Well, I would be very thankful if at some point you'd have time to look into that indeed. And now worries, I have the same issue with time so even a few months would be perfectly fine :)

**Comment by marcolaux** [comment]
Hi @ned-si 

I'm beginnig to actively support it as I'm using SN again.

I can't replicate that issue anymore. Do you still have it?

Btw I change the installation URL to (you probably would need to remove and install it again)::
https://laux.wtf/sn/vscode-theme/ext.json

**Comment by ned-si** [comment]
Thanks for the feedback.

I changed the URL (removed and reinstalled" the theme using the new one you just linked. It worked fine on desktop - I went form 1.0.x to 1.1.8. 

Unfortunately, on mobile, after restarting the app, I have the following error:

```
Not Available
This theme is not available on mobile.
```

Am I doing something wrong?

**Comment by marcolaux** [comment]
nothing wrong on your side

I thought I fixed this. I minified the distributed CSS and that also caused this error for me.
But lately I don't minify it and it worked for me.

Could you try the following?

- within the app open the menu with the themes
- touch and hold the finger on the VS Code theme
- a menu should appear with the option to "re-download" -> use this to redownload the theme

Does it work now?

**Comment by ned-si** [comment]
I didn't know there was a hold menu on the themes, interesting!

I redownloaded it and, unfortunately, still the same error (also after restarting the app).

**Comment by marcolaux** [comment]
thanks for the feedback
this is really odd. do you use the newest version 3.9.3?

**Comment by marcolaux** [comment]
hmm. perhaps you have to remove it from the desktop first and re-add it there
as it gets synced with the desktop perhaps there is still some conflict and the android version is using a cached version that is not the current one (?)

**Comment by marcolaux** [comment]
but you said already that you removed it
I'm out of ideas at the moment :(

**Comment by ned-si** [comment]
3.9.3 on mobile yep, and 3.9.4 on desktop.

> perhaps you have to remove it from the desktop first and re-add it there

That's what I did as I don't think we can uninstall/reinstall directly from the mobile app actually.

Well, I guess that 3.9.4 will arrive on mobile soon, I will test again then.

**Comment by marcolaux** [comment]
> Well, I guess that 3.9.4 will arrive on mobile soon, I will test again then.

Thank you, appreciated.
I'll also look at some time if I can reproduce it. At the moment I strangely can't and it works on my device at least.

I'm not sure if the css file gets transfered from the desktop version to your account and not directly downloaded from my hosting. The last idea that would come to my mind is that you extract the zip `https://laux.wtf/sn/vscode-theme/vscode-theme.zip` to `~/.config/Standard Notes/Extensions/vscode-theme` manually.

When I develop the theme I sometimes have the issue that the current state does not get downloaded and I have to override the files manually.

And then on the mobile app redownload - but as I'm writing this I don't feel that this makes sense as the desktop app does not then automatically reupload everything to your account.
Ahh well :grimacing:

**Comment by marcolaux** [comment]
There is definitely some weird caching behaviour going on.

I never saw the newest styles on the android app in the editors lately.
I just added my newest theme version to the desktop app (uninstalled the theme first), redownloaded on mobile and now also the editor styles are there.

**Comment by ned-si** [comment]
Don't know if the info helps, but I just tried to uninstall / reinstall it on mobile and it doesn't seem to make any difference.

**Comment by marcolaux** [comment]
I'll try it later today with another phone / account.

**Comment by marcolaux** [comment]
Hi @ned-si 
could you try to reinstall again?
@xthursdayx  made a PR to make it more compatible with the SN Community Extension Repo.
Perhaps it works also better for you now.

Keep in mind that the URL also changed.

**Comment by ned-si** [comment]
Hey @hyphone,

Sorry, I completely forgot about this and continued using your them nonetheless. But I just thought about it again and reinstalled it with the proper url (the process is slightly different than in the README now) and everything is working perfectly!

Cheers!

**Comment by marcolaux** [comment]
@ned-si 

cool, thanks for coming back to it!
